name = "blog"
type = "webpack"
account_id = "${{ CF_ACCOUNT_ID }}"
workers_dev = false
route = "blog.juanito87.com.ar/*"
zone_id = "${{ CF_ZONE_ID }}"

[site]
bucket = "./public"
entry-point = "workers-site"
