# This is a basic workflow to help you get started with Actions

name: Deploy to cloudflare

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup latest hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Build the site
      - name: Build site
        run: hugo

      # Publish to cloudflare workers
      - name: Publish to cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        env:
            USER: root
            CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
            CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
